import type { Move } from '../types';

export const mockMoves: Move[] = [
    {
        id: '1',
        title: 'Lakefill Frisbee',
        category: 'Sports',
        timeRange: '14:00 - 16:00',
        status: 'Live Now',
        participants: 6,
        maxParticipants: 10,
        notes: 'Free / Bring water',
        isJoined: false,
        isSaved: false,
        isHost: false,
        location: 'Lakefill',
        exactMeetingSpot: 'Meet near the sailing center rocks.',
        comments: [
            { user: 'John', text: 'Bring water!' },
            { user: 'Sarah', text: 'I have an extra frisbee if needed' },
        ],
    },
    {
        id: '2',
        title: 'Study Sesh',
        category: 'Study',
        timeRange: '18:00 - 20:00',
        status: 'Upcoming',
        participants: 3,
        isJoined: false,
        isSaved: false,
        isHost: false,
        location: 'Tech LR5',
        exactMeetingSpot: 'Room 5, bring your student ID.',
        comments: [
            { user: 'Mike', text: 'What topics are we covering?' },
        ],
    },
    {
        id: '3',
        title: 'Coffee Chat',
        category: 'Social',
        timeRange: '12:00 - 14:00',
        status: 'Past',
        participants: 4,
        isJoined: false,
        isSaved: false,
        isHost: false,
        location: 'Caffeine',
        exactMeetingSpot: 'Outdoor seating area.',
        comments: [],
    },
    {
        id: '4',
        title: 'Basketball Pickup',
        category: 'Sports',
        timeRange: '16:00 - 18:00',
        status: 'Live Now',
        participants: 8,
        maxParticipants: 12,
        notes: 'Bring your own ball',
        isJoined: false,
        isSaved: false,
        isHost: false,
        location: 'SPAC Courts',
        exactMeetingSpot: 'Court 3 entrance.',
        comments: [
            { user: 'Alex', text: 'Need 2 more players!' },
            { user: 'Jordan', text: 'I\'m bringing the ball' },
        ],
    },
];